#ifndef _HARDWARE_MANAGER_H
#define _HARDWARE_MANAGER_H

#include "ssd1306.h"
#include "hardware/adc.h"
#include "hardware/pwm.h"
#include "hardware/i2c.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"

// Bib generated by compilation process
#include "ws2818b.pio.h"

#include "pico/stdlib.h"

// Button GPIOs
#ifndef BUTTON_A_PIN
#define BUTTON_A_PIN 5
#endif
#ifndef BUTTON_B_PIN
#define BUTTON_B_PIN 6
#endif

#ifndef JOYSTICK_SW_PIN
#define JOYSTICK_SW_PIN 22
#endif

// LEDs pins
#ifndef RED_LED_PIN 
#define RED_LED_PIN 13
#endif

#ifndef BLUE_LED_PIN
#define BLUE_LED_PIN 12
#endif

#ifndef GREEN_LED_PIN
#define GREEN_LED_PIN 11
#endif

// OLED display dimensions
#ifndef OLED_WIDTH
#define OLED_WIDTH 128
#endif

#ifndef OLED_HEIGHT
#define OLED_HEIGHT 64
#endif

// I2C defines for the OLED display
#ifndef I2C_PORT
#define I2C_PORT i2c1 // Default to i2c1
#endif

#ifndef I2C_SDA_PIN
#define I2C_SDA_PIN 14 // Default SDA pin for i2c1
#endif

#ifndef I2C_SCL_PIN
#define I2C_SCL_PIN 15 // Default SCL pin for i2c1
#endif

#ifndef SSD1306_I2C_ADDR
#define SSD1306_I2C_ADDR 0x3C // Default I2C address for SSD1306
#endif

// Joystick movement thresholds
#ifndef JOYSTICK_THRESHOLD_HIGH
#define JOYSTICK_THRESHOLD_HIGH 3000
#endif

#ifndef JOYSTICK_THRESHOLD_LOW
#define JOYSTICK_THRESHOLD_LOW 1000
#endif

// Mic channels and pins
#ifndef MIC_CHANNEL
#define MIC_CHANNEL 2
#endif

#ifndef MIC_PIN
#define MIC_PIN (26 + MIC_CHANNEL)
#endif

// Joystick ADC GPIOs
#ifndef JOYSTICK_VRX_PIN
#define JOYSTICK_VRX_PIN 27 // Connected to GP27 (ADC1)
#endif

#ifndef JOYSTICK_VRY_PIN
#define JOYSTICK_VRY_PIN 26 // Connected to GP26 (ADC0)
#endif

// Buzzer pins
#ifndef BUZZER_A_PIN
#define BUZZER_A_PIN 21
#endif

#ifndef BUZZER_B_PIN
#define BUZZER_B_PIN 10
#endif

// Matrix LEDs 
#define MATRIX_LED_COUNT 25
#define MATRIX_LED_PIN 7

static bool _init_display(ssd1306_t *disp);
static void _init_buttons();
static void _init_leds();
static void _init_mic();
static void _init_joystick();
static void _init_audio();
static void _init_matrix_led();
bool init_hardware(ssd1306_t *disp);

void npSetLED(const uint index, const uint8_t r, const uint8_t g, const uint8_t b);
void npClear();
void npWrite();

#endif